pathes:
  input_data_path: "data/heart_cleveland_upload.csv"
  output_model_path: "models/model.pkl"
  metric_path: "models/metrics.json"
  data_url: "https://drive.google.com/u/0/uc?id=1kdhrRDg1NaHoJ9jmnOsABPsBucoezDLp&export=download"
train_params:
  SEED : 322
  input_size : 13
  num_classes : 2
  learning_rate : 0.001
  batch_size : 1
  num_epochs : 200
  weight_decay: 0.0001
splitting_params:
  manual_seed : 322
  train_percentage: 0.75
predict_params:
  path_to_data: "data/data_to_predict.csv"
  path_to_model: "models/model.pkl"
  output_path: "predicts/scores.csv"